[package]
name = "grrs"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.1.0"
inquire = "0.7.5"
dialoguer = "0.11.0"
ramhorns = "1.0.0"
same-file = "1.0.6"

lopdf = "0.36.0"