openapi: 3.0.0
info:
  version: "0.0.1"
  title: ""
paths:
  /application:
    get:
      tags:
        - application
      description: "GET existing application with Id"
      parameters:
        - in: query
          name: rust_query_object
          explode: true
          schema:
            $ref: "#/components/schemas/get_application_query_parameters"
      responses:
        "200":
          $ref: "#/components/schemas/applicationGetResponse"

components:
  schemas:


    get_application_query_parameters:
      type: object
      description: rust struct for parsing query parameters
      properties:
        applicationId:
          type: string


    application:
      type: object
      description: Application object
      properties:
        id:
          type: string
          description: applicationId

    applicationGetResponse:
      type: object
      description: Get application by Id
      properties: #        application:
        #          $ref: "#/components/schemas/application"
        test:
          type: string



